### ISSUE TITLE
vertx-service-proxy difference

### ISSUE THREAD

**Issue by manikantag** [nsforth/vxrifa#1]
Hi,

How is this different from **vertx-service-proxy** (https://vertx.io/docs/vertx-service-proxy/java/)? Thanks

**Comment by nsforth** [comment]
Hi, thanks for your interest!
VxRifa is not service-oriented. It allows creation of "publish" or "request-response" interfaces so you can write classic java-style listener's for example. In contrast vertx-service-proxy can make only request-response services.
Also VxRifa do not try to coexists with other languages and supports only Java and Java programming style. For example you can define interfaces with any parameters that you want without restrictions. Of course immutability of complex objects and serialization if needed is your responsibility.
There are some planned features that should differentiate it more:
1. Automatic load balancing between services that implements same interface.
2. Integration with some dependency injection frameworks for example Dagger2 so it should be possible to deploy verticles on demand and simplify application structure and bootstrap.

**Comment by manikantag** [comment]
Got it.

About the automatic load balancing, I think Vertx event bus itself handles that. Quoting Vertx docs (https://vertx.io/docs/vertx-core/java/#_the_theory):

> **Point to point and Request-Response messaging**
> ... 
> **If there is more than one handler registered at the address, one will be chosen using a non-strict round-robin algorithm.**

What else are you referring when you say it is a planned feature? Thanks.

**Comment by vaIgarashi** [comment]
Yes, when you use `VxRifaUtil.getSenderByInterface()` will be used round-robin algorithm

**Comment by manikantag** [comment]
Got it. Thanks
