### ISSUE TITLE
"@Generated" annotation

### ISSUE THREAD

**Issue by katol** [nsforth/vxrifa#10]
Hello. 
Our company used Java 8 with vert.x and vxrifa, but now we are migrating to Java 11. 
We have found, that "javax.annotation.Generated" now located in "javax.annotation.processing.Generated". 
But vxrifa generates it's classes with "import javax.annotation.Generated;".

**Comment by nsforth** [comment]
Hi. Planned to 1.4.0 version! :)
Vert.X minimum supported version must be upgraded too. There are some caveats, but it won't be hard though.

**Comment by nsforth** [comment]
1.4.0 version released.
